function bhlpfun(hlpname,titleStr,helpStr1,helpStr2,helpStr3,helpStr4,helpStr5,helpStr6,helpStr7,helpStr8,helpStr9);
% bhlpfun(hlpname,titleStr,helpStr1,helpStr2,helpStr3,helpStr4,helpStr5,helpStr6,helpStr7,helpStr8,helpStr9);
% BHLPFUN Utility function for displaying help text conveniently.

% titleStr is Name of a Page
% hlpname is name of the help window
% Length of a Column of helpStr1, helpStr2,... is  not more than 70 characters.

% Binh 4-27-95 for every Helpname and more Page


% The Help Window without Help-Text can be displayed.
if nargin <3,
   error('Three Input Arguments at least required.');
end
numPages=nargin-2;

ttlSize=size(titleStr);
% Hat titleStr viele Zeile, dann hat jede Seit einen eigenen Namen.
% aber die Anzahl der Zeilen kann nur 1 oder die Anzahl von Seiten sein.
% titleStr muss EinSpaltVektor von Strings  sein.

if (ttlSize(1) == 1),
   TitleStr=titleStr; 
   for i=2:numPages, TitleStr=[TitleStr,titleStr]; end
end
if (ttlSize >1),
   if (numPages ~= ttlSize),
      error('Number of Titles must be equal Number of Pages.');
   else
      TitleStr=[];
      for i=1:ttlSize, TitleStr=[TitleStr,titleStr(i,:)];end
   end
end


% First turn on the watch pointer in the old figure
oldFigNumber=watchon;

Pagenumber=1;


% If the Help Window has already been created, bring it to the front
[existFlag,figNumber]=figflag(hlpname,1);
newHelpWindowFlag=~existFlag;

if newHelpWindowFlag,
    ssUnits=get(0,'Units');
    set(0,'Units','Pixels'); ss=get(0,'ScreenSize');
    if ss(3:4)==[640 480],
      myleft=70;mybottom=40;mywidth=500;myheight=400;
    else
       mywidth = .4*ss(3); myheight = .5*ss(4);
       mybottom = .5*(ss(4)-myheight);
       myleft = .5*(ss(3)-mywidth);
    end
    position=[myleft mybottom mywidth myheight];
    figNumber=figure( ...
        'Name',hlpname, ...
        'NumberTitle','off', ...
        'NextPlot','new', ...
	'Visible','off', ...
	'Position',position, ...
	'Color',[.5 0 0],'Resize','off');

    %===================================
    % Set up the Help Window
    top=0.95;
    left=0.05;
    right=0.75;
    bottom=0.05;
    labelHt=0.03;  
    spacing=0.005;

    % First, the Text Window frame
    frmBorder=0.02;
    frmPos=[left-frmBorder bottom-frmBorder ...
        (right-left)+2*frmBorder (top-bottom)+2*frmBorder];
    uicontrol( ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
	'BackgroundColor',[0.5 0.5 0.5]);
    % Then the text label
    labelPos=[left top-labelHt (right-left) labelHt];
    ttlName=deblank(TitleStr(1:ttlSize(2)));
    ttlHndl=uicontrol( ...
	'Style','text', ...
        'Units','normalized', ...
        'Position',labelPos, ...
        'BackgroundColor',[0.5 0.5 0.5], ...
        'ForegroundColor',[1 1 1], ...
        'String',ttlName);
    % Then the editable text field (of which there are three)
    % Store the text field's handle two places: once in the figure
    % UserData and once in the button's UserData.
    for count=1:numPages,
    	helpStr=eval(['helpStr',num2str(count)]);
    	txtPos=[left bottom (right-left) top-bottom-labelHt-spacing];
    	txtHndlList(count)=uicontrol( ...
    	    'Style','edit', ...
    	    'Units','normalized', ...
    	    'Max',20, ...
    	    'String',helpStr, ...
    	    'BackgroundColor',[1 1 1], ...
	    'Visible','off', ...
    	    'Position',txtPos);
    end;
    set(txtHndlList(1),'Visible','on');

    %====================================
    % Information for all buttons
    labelColor=[0.8 0.8 0.8];
    top=0.95;
    bottom=0.05;
    yInitPos=0.80;
    left=0.80;
    btnWid=0.15;
    btnHt=0.08;
    % Spacing between the button and the next command's label
    spacing=0.05;

    %====================================
    % The CONSOLE frame
    frmBorder=0.02;
    yPos=bottom-frmBorder;
    frmPos=[left-frmBorder yPos btnWid+2*frmBorder 0.9+2*frmBorder];
    uicontrol( ...
        'Style','frame', ...
        'Units','normalized', ...
        'Position',frmPos, ...
	'BackgroundColor',[0.5 .5 0.5]);

    %====================================
    % All required BUTTONS
    %=====Begin of the change by Binh====
    % The callback will turn off ALL text fields and then turn on
    % only the one referred to by the button.
    callbackStr1= ...
      ['hndlList=get(gcf,''UserData'');', ...
       'ttlPages=get(gco,''UserData'');',... 
       'numPages=hndlList(1);Pagenumber=hndlList(2);',...
       'tS=hndlList(numPages+6:numPages+7);',...
       'if Pagenumber > 1,',...
          'Pagenumber=Pagenumber-1;',...
          'ttlP=ttlPages((Pagenumber-1)*tS(2)+1:Pagenumber*tS(2));',...
          'set(hndlList(4:numPages+3),''Visible'',''off'');', ...
	  'set(hndlList(Pagenumber+3),''Visible'',''on'');',...
          'hndlList(2)=Pagenumber;',...
          'set(hndlList(3),''String'',deblank(ttlP));',...
          'set(gcf,''UserData'',hndlList);',...
       'end'];

    callbackStr2= ...
      ['hndlList=get(gcf,''UserData'');', ...
       'ttlPages=get(gco,''UserData'');',... 
       'numPages=hndlList(1);Pagenumber=hndlList(2);',...
       'tS=hndlList(numPages+6:numPages+7);',...
       'if Pagenumber < numPages,',...
          'Pagenumber=Pagenumber+1;',...
          'ttlP=ttlPages((Pagenumber-1)*tS(2)+1:Pagenumber*tS(2));',...
          'set(hndlList(4:numPages+3),''Visible'',''off'');', ...
	  'set(hndlList(Pagenumber+3),''Visible'',''on'');',...
          'hndlList(2)=Pagenumber;',...
          'set(hndlList(3),''String'',deblank(ttlP));',...
          'set(gcf,''UserData'',hndlList);',...
       'end'];
 
    btnHndlList(1)= uicontrol( ...
    	    'Style','pushbutton', ...
    	    'Units','normalized', ...
    	    'Position',[left top-btnHt btnWid btnHt], ...
    	    'String','Back', ...
	    'Visible','off', ...
            'UserData',TitleStr, ...
    	    'Callback',callbackStr1);
    btnHndlList(2)= uicontrol( ...
    	    'Style','pushbutton', ...
    	    'Units','normalized', ...
    	    'Position',[left top-2*btnHt-spacing btnWid btnHt], ...
    	    'String','Next', ...
	    'Visible','off', ...
            'UserData',TitleStr, ...
    	    'Callback',callbackStr2);

    %============End of change===========
    %====================================
    % The CLOSE button
    callbackStr= ...
	['f1=gcf; f2=gpf; set(f1,''Visible'',''off'');', ...
	 'if f1~=f2, figure(f2); end'];
    uicontrol( ...
        'Style','pushbutton', ...
        'Units','normalized', ...
        'Position',[left 0.05 btnWid btnHt], ...
        'String','Close', ...
        'Callback',callbackStr);
 
    hndlList=[numPages Pagenumber ttlHndl txtHndlList btnHndlList ttlSize];
        
    set(figNumber,'UserData',hndlList);
end;

% Now that we've determined the figure number, we can install the
% Desired strings.
hndlList=get(figNumber,'UserData');
ttlHndl=hndlList(3);
txtHndlList=hndlList(4:numPages+3);
btnHndlList=hndlList(numPages+4:numPages+5);
ttlName=deblank(TitleStr(1:ttlSize(2)));
set(ttlHndl,'String',ttlName);
set(txtHndlList(1),'Visible','on');
set(txtHndlList(2:numPages),'Visible','off');
for i=1:numPages,
   bhelpstr=eval(['helpStr',num2str(i)]);
   set(txtHndlList(i),'String',bhelpstr);
end

if numPages==1,
    set(btnHndlList,'Visible','off');
else
    set(btnHndlList,'Visible','on');
end

set(figNumber,'Visible','on');
% Turn off the watch pointer in the old figure
watchoff(oldFigNumber);
figure(figNumber);
