% Demo of GA toolbox, GRAFical user interface
%
% This script is a grafical interface to the Genetic Algorithm Toolbox.
% It provides an interactive control for nearly all parameters of the
% toolbox. The optimization can be followed online. Most of the
% parameters can be changed online as well (that means during the
% optimization) taking effect immediatelly.
%
% Syntax:  dgagraf
%
% See also: dgampga, dganew, dgamesh, genalg1

% Author:     Hartmut Pohlheim
% History:    09.04.94     file created


OPTLOOP_F = 'dgampga';
GUILOOP_F = 'dgagraf';
NEWINIT_F = 'dganew';

if ~exist('command'), command = 'new';
elseif isempty(command), command = 'new'; 
end 

if strcmp(lower(command),'new'),

   % get all the default parameters 
   eval(NEWINIT_F);
   RunFlag = 0;

   % look for figure, set Name
   fig1 = findobj('UserData', 'demogatoolbox_figinterface');
   if isempty(fig1),
      fig1 = figure('UserData', 'demogatoolbox_figinterface');
   end
   figure(fig1);
   set(fig1, 'NumberTitle', 'Off', ...
             'Name', 'Genetic Algorithm Toolbox Interface',...
             'Color', 'b', ...
             'Position', [10 10 530 400],... 
             'resize','on'); 
   set(fig1, 'DefaultTextFontSize', 9);

   Ax2 = axes( 'Position', [0 0 1 1], 'Units', 'Normalized' ) ;
   axis( 'off' ) ;


   %Define positions and distances for grafical elements
   high1 = 0.045; high2 = 0.052; high0 = 0.99 - high2; 
   widepb = 0.1; wideed = 0.14; widesl = 0.32; widerb = 2*widesl/3; 
   left1 = 0.02; left2 = 0.15; left3 = 0.38;
   left4 = left3 + wideed + 0.02; left5 = left4 + 0.03;
   left6 = left5 + widesl + 0.01;

   command = 'uiinit';
   eval(GUILOOP_F);

elseif strcmp(lower(command),lower('uiinit')) 

   oldaxes = gca;
   axes(Ax2);
   cla;
   axes(oldaxes);

   %  Uicontrol Object Creation 
   highrun = 0.02;
   pushb1 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''quit''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Quit',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['pushb1']); 

   highrun = highrun + 2 * high2;
   pushb6 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''reset''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Reset',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['pushb6']);  

   highrun = highrun + 2 * high2;
   pushb2 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''init''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Init',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['pushb2']); 

   highrun = highrun + 2 * high2;
   pushb3 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''stop''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Stop',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['pushb3']); 

   highrun = highrun + 2 * high2;
   pushb4 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''step''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Step',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['pushb4']);  

   highrun = highrun + 2 * high2;
   pushb5 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command = ''run''; eval(GUILOOP_F)',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position',[left1 highrun widepb 2*high1],... 
      'String','Run',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'Interruptible','yes',...
      'UserData',['pushb5']); 

   highrun = high0;
   sl1text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Generations',...
      'VerticalAlignment','bottom') ;
   sl1edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MAXGEN=ceil(str2num(get(sl1edit,''String'')));'...
                  'MAXGEN=max(1,MAXGEN);'...
                  'set(sl1edit,''String'',int2str(MAXGEN));'...
                  'set(sl1,''Value'',MAXGEN);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',int2str(MAXGEN),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl1edit']); 
   sl1text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;
   sl1 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MAXGEN=ceil(get(sl1,''Value''));'...
                  'set(sl1edit,''String'',int2str(MAXGEN));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 1, 'Max', max(1000,MAXGEN),...
      'Position', [left5 highrun widesl high1],...
      'String',' ',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', MAXGEN, ...
      'Visible','on',... 
      'UserData',['sl1']);
   sl1text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String',int2str(get(sl1,'Max')),...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2;
   sl8text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Plot interval',...
      'VerticalAlignment','bottom') ;
   sl8edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['PLOTTIME=ceil(str2num(get(sl8edit,''String'')));'...
                  'PLOTTIME=max(1,PLOTTIME);'...
                  'set(sl8edit,''String'',int2str(PLOTTIME));'...
                  'set(sl8,''Value'',PLOTTIME);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',int2str(PLOTTIME),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl8edit']); 
   sl8text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;
   sl8 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['PLOTTIME=ceil(get(sl8,''Value''));'...
                  'set(sl8edit,''String'',int2str(PLOTTIME));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 1, 'Max', 100,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', PLOTTIME, ...
      'Visible','on',... 
      'UserData',['sl8']);
   sl8text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','100',...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2;
   sl4text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Generation gap',...
      'VerticalAlignment','bottom') ;
   sl4edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['GGAP=str2num(get(sl4edit,''String''));'...
                  'GGAP=max(0,GGAP);'...
                  'set(sl4edit,''String'',num2str(GGAP));'... 
                  'set(sl4,''Value'',GGAP);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(GGAP),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl4edit']); 
   sl4text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl4 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['GGAP=get(sl4,''Value'');'...
                  'set(sl4edit,''String'',num2str(GGAP));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 0, 'Max', 2,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', GGAP, ...
      'Visible','on',... 
      'UserData',['sl4']);
   sl4text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','2',...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2;
   sl2text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Mutation rate',...
      'VerticalAlignment','bottom') ;
   sl2edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MUTR=str2num(get(sl2edit,''String''));'...
                  'MUTR=min(1,max(0,MUTR));'...
                  'set(sl2edit,''String'',num2str(MUTR));'... 
                  'set(sl2,''Value'',log2(MUTR));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(MUTR),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl2edit']); 
   sl2text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl2 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MUTR=2^get(sl2,''Value'');'...
                  'set(sl2edit,''String'',num2str(MUTR));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', -20, 'Max', 0,...
      'Position', [left5 highrun widesl high1],...
      'String',' ',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', log2(MUTR), ...
      'Visible','on',... 
      'UserData',['sl2']);
   sl2text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;


   highrun = highrun - high2;
   sl3text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Shrink mutation',...
      'VerticalAlignment','bottom') ;
   sl3edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MUTSHRINK=str2num(get(sl3edit,''String''));'...
                  'MUTSHRINK=min(1,max(0,MUTSHRINK));'...
                  'set(sl3edit,''String'',num2str(MUTSHRINK));'... 
                  'set(sl3,''Value'',log10(MUTSHRINK));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(MUTSHRINK),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl3edit']); 
   sl3text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl3 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MUTSHRINK=10^(get(sl3,''Value''));'...
                  'set(sl3edit,''String'',num2str(MUTSHRINK));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', -15, 'Max', 0,...
      'Position', [left5 highrun widesl high1],...
      'String','M ',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', log10(MUTSHRINK), ...
      'Visible','on',... 
      'UserData',['sl3']);
      % MUTSHRINK=1e(get(sl3,''Value''));
   sl3text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;



   highrun = highrun - high2;
   sl6text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Migration time',...
      'VerticalAlignment','bottom') ;
   sl6edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MIGGEN=ceil(str2num(get(sl6edit,''String'')));'...
                  'MIGGEN=max(1,MIGGEN);'...
                  'set(sl6edit,''String'',int2str(MIGGEN));'... 
                  'set(sl6,''Value'',MIGGEN);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',int2str(MIGGEN),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl6edit']); 
   sl6text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl6 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MIGGEN=ceil(get(sl6,''Value''));'...
                  'set(sl6edit,''String'',int2str(MIGGEN));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 0, 'Max', 100,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', MIGGEN, ...
      'Visible','on',... 
      'UserData',['sl6']);
   sl6text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','100',...
      'VerticalAlignment','bottom') ;


   highrun = highrun - high2;
   sl7text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Migration rate',...
      'VerticalAlignment','bottom') ;
   sl7edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MIGR=str2num(get(sl7edit,''String''));'...
                  'MIGR=min(1,max(0,MIGR));'...
                  'set(sl7edit,''String'',num2str(MIGR));'... 
                  'set(sl7,''Value'',MIGR);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(MIGR),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl7edit']); 
   sl7text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl7 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MIGR=get(sl7,''Value'');'...
                  'set(sl7edit,''String'',num2str(MIGR));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 0, 'Max', 1,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', MIGR, ...
      'Visible','on',... 
      'UserData',['sl7']);
   sl7text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;


   highrun = highrun - high2;
   pop4text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Migr. structure',...
      'VerticalAlignment','bottom') ;
   pop4 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['MIGTOPO=get(pop4,''Value'')-1;'],...
      'ForegroundColor',[0 0 0 ],... 
      'Max', 3,...
      'Position', [left3 highrun widesl high1],...
      'String',' Unrestricted | Neighbourhood | Ring ',... 
      'Style','popupmenu',... 
      'Units','normalized',... 
      'Value', MIGTOPO-1,...
      'Visible','on',... 
      'UserData',['pop4']); 


   highrun = highrun - high2;
   sl9text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Sel. pressure',...
      'VerticalAlignment','bottom') ;
   if ~RANKMETH, spmax = 2; else spmax = NVAR - 2; end
   sl9edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['SP=str2num(get(sl9edit,''String''));,'...
                  'SP=min(spmax,max(1,SP));'...
                  'set(sl9,''Value'',SP);'...
                  'set(sl9edit,''String'',num2str(SP));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(SP),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl9edit']); 
   sl9text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;
   sl9 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['SP=get(sl9,''Value'');'...
                  'set(sl9edit,''String'',num2str(SP));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 1, 'Max', spmax,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', SP, ...
      'Visible','on',... 
      'UserData',['sl9']);
   sl9text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String',int2str(spmax),...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2;
   radio2text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Ranking',...
      'VerticalAlignment','bottom') ;
   radio2(1) = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['RANKMETH = ~get(radio2(1),''Value'');'...
                  'set(radio2(2),''Value'',RANKMETH);'...
                  'command = ''checkrankmax''; eval(GUILOOP_F);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun widerb high1],...
      'String','Linear',... 
      'Style','radiobutton',... 
      'Units','normalized',... 
      'Value', ~RANKMETH,...
      'Visible','on',... 
      'UserData',['radio2(1)']); 
   radio2(2) = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['RANKMETH = get(radio2(2),''Value'');'...
                  'set(radio2(1),''Value'',~RANKMETH);'... 
                  'command = ''checkrankmax''; eval(GUILOOP_F);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left5+widesl-widerb highrun widerb high1],...
      'String','Non-linear',... 
      'Style','radiobutton',... 
      'Units','normalized',... 
      'Value', RANKMETH,...
      'Visible','on',... 
      'UserData',['radio2(2)']); 

   highrun = highrun - high2;
   pop1text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Selection',...
      'VerticalAlignment','bottom') ;
   if strcmp('selrws',lower(SEL_F)), valpop1=1;
   elseif strcmp('selsus',lower(SEL_F)), valpop1=2;
   elseif strcmp('sellocal',lower(SEL_F)), valpop1=3;
   elseif strcmp('seltrunc',lower(SEL_F)), valpop1=4;
   else valpop1=2; end
   pop1 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['valpop1=get(pop1,''Value'');'...
                  'if valpop1==1,SEL_F=''selrws'';'...
                  'elseif valpop1==2,SEL_F=''selsus'';'...
                  'elseif valpop1==3,SEL_F=''sellocal'';'...
                  'elseif valpop1==4,SEL_F=''seltrunc'';'...
                  'else SEL_F=''selsus'';end'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Max', 4,...
      'Position', [left3 highrun widesl high1],...
      'String',[' Roulette (selrws) | Stochastic (selsus) '...
               '| Local (sellocal) | Trunc (seltrunc) '],...
      'Style','popupmenu',... 
      'Units','normalized',... 
      'Value', valpop1,...
      'Visible','on',... 
      'UserData',['pop1']); 

   highrun = highrun - high2;
   pop2text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Recombination',...
      'VerticalAlignment','bottom') ;
   if strcmp('recdis',lower(XOV_F)), valpop2=1;
   elseif strcmp('recint',lower(XOV_F)), valpop2=2;
   elseif strcmp('reclin',lower(XOV_F)), valpop2=3;
   elseif strcmp('xovsp',lower(XOV_F)), valpop2=4;
   elseif strcmp('xovdp',lower(XOV_F)), valpop2=5;
   elseif strcmp('xovsh',lower(XOV_F)), valpop2=6;
   else valpop2=1; end
   pop2 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command=''checkrecombine'';eval(GUILOOP_F);',...
      'ForegroundColor',[0 0 0 ],... 
      'Max', 6,...
      'Position', [left3 highrun widesl high1],...
      'String',[' Discret (recdis) | Intermediate (recint) | '...
                'Line (reclin) | Single (xovsp) | '...
                'Double (xovdp) | Shuffle (xovsh) '],... 
      'Style','popupmenu',... 
      'Units','normalized',... 
      'Value', valpop2,...
      'Visible','on',... 
      'UserData',['pop2']); 

   highrun = highrun - high2;
   pop3text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Mutation',...
      'VerticalAlignment','bottom') ;
   if strcmp('mutbga',lower(MUT_F)), valpop3=1;
   elseif strcmp('mutbint',lower(MUT_F)), valpop3=2;
   else valpop3=1; end
   pop3 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','command=''checkmutate'';eval(GUILOOP_F);',...
      'ForegroundColor',[0 0 0 ],... 
      'Max', 2,...
      'Position', [left3 highrun widesl high1],...
      'String',[' Breeder (mutbga) | Binary (mutbint) '],... 
      'Style','popupmenu',... 
      'Units','normalized',... 
      'Value', valpop3,...
      'Visible','on',... 
      'UserData',['pop3']); 

   highrun = highrun - high2;
   fl1text = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Filename',...
      'VerticalAlignment','bottom');
   fl1 = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack','',... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun widerb high1],...
      'String','datademo',... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['fl1']); 
   fl2 = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'Callback',['save_str=get(fl1,''String'');'...
                  'command =''save'';eval(GUILOOP_F)'],...
      'ForegroundColor',[0 0 0 ],... 
      'Position',[(left3+widerb+left5+widesl)/2-widepb highrun widepb high1],...
      'String','Save',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['fl2']);
   fl3 = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'Callback',['save_str=get(fl1,''String'');'...
                  'command =''load'';eval(GUILOOP_F)'],...
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left5+widesl-widepb highrun widepb high1],...
      'String','Load',... 
      'Style','pushbutton',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['fl3']);

   highrun = highrun - high2 - 0.01;
   NINDNew = NIND;
   sl10text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Individuals',...
      'VerticalAlignment','bottom') ;
   sl10edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['NINDNew=ceil(str2num(get(sl10edit,''String'')));'...
                  'NINDNew=max(1,NINDNew);'...
                  'set(sl10edit,''String'',int2str(NINDNew));'...
                  'set(sl10,''Value'',NINDNew);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',int2str(NINDNew),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl10edit']); 
   sl10text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;
   sl10 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['NINDNew=ceil(get(sl10,''Value''));'...
                  'set(sl10edit,''String'',int2str(NINDNew));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 1, 'Max', 100,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', NINDNew, ...
      'Visible','on',... 
      'UserData',['sl10']);
   sl10text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','100',...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2;
   SUBPOPNew = SUBPOP;
   sl11text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Subpopulations',...
      'VerticalAlignment','bottom') ;
   sl11edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['SUBPOPNew=ceil(str2num(get(sl11edit,''String'')));'...
                  'SUBPOPNew=max(1,SUBPOPNew);'...
                  'set(sl11edit,''String'',int2str(SUBPOPNew));'...
                  'set(sl11,''Value'',SUBPOPNew);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',int2str(SUBPOPNew),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl11edit']); 
   sl11text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;
   sl11 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['SUBPOPNew=ceil(get(sl11,''Value''));'...
                  'set(sl11edit,''String'',int2str(SUBPOPNew));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 1, 'Max', 50,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', SUBPOPNew, ...
      'Visible','on',... 
      'UserData',['sl11']);
   sl11text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','50',...
      'VerticalAlignment','bottom') ;

   highrun = highrun - high2-0.01;
   CODEREALNew = CODEREAL;
   radio1text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Coding',...
      'VerticalAlignment','bottom') ;
   radio1(1) = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['CODEREALNew = get(radio1(1),''Value'');'...
                  'set(radio1(2),''Value'',~CODEREALNew);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun widerb high1],...
      'String','Binary',... 
      'Style','radiobutton',... 
      'Units','normalized',... 
      'Value', CODEREALNew,...
      'Visible','on',... 
      'UserData',['radio1(1)']); 
   radio1(2) = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['CODEREALNew = ~get(radio1(2),''Value'');'...
                  'set(radio1(1),''Value'',CODEREALNew);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left5+widesl-widerb highrun widerb high1],...
      'String','Real',... 
      'Style','radiobutton',... 
      'Units','normalized',... 
      'Value', ~CODEREALNew,...
      'Visible','on',... 
      'UserData',['radio1(2)']); 

   highrun = highrun - high2;
   OBJ_FNew = OBJ_F;
   obj1text = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Function',...
      'VerticalAlignment','bottom');
   obj1 = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['OBJ_FNew=get(obj1,''String'');'...
                  'if exist(OBJ_FNew)<2, OBJ_FNew=OBJ_F; end;'...
                  'set(obj1,''String'',OBJ_FNew);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun widerb high1],...
      'String', OBJ_FNew,... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['obj1']); 

   actiontext = text(...
      'Color',[1 1 1 ],... 
      'EraseMode','background',... 
      'Position',[left1 high0 0],... 
      'String','',...
      'VerticalAlignment','bottom');

   % initialize
   command = 'init';
   eval(GUILOOP_F);

elseif strcmp(lower(command),lower('quit')) 
   if RunFlag,
      command = 'stop';
      eval(GUILOOP_F);
   end
   fig1quit = findobj('UserData', 'demogatoolbox_figinterface');
   if ~isempty(fig1quit), figure(fig1quit); close(fig1quit); end
   fig2quit = findobj('UserData', 'demogatoolbox_figmeshplot');
   if ~isempty(fig2quit), figure(fig2quit); close(fig2quit); end
   fig3quit = findobj('UserData', 'gatoolbox_figresplot');
   if ~isempty(fig3quit), figure(fig3quit); close(fig3quit); end
   clear command;
   break;   

elseif strcmp(lower(command),lower('reset')) 
   if RunFlag,
      command = 'stop';
      eval(GUILOOP_F);
   end
   eval(NEWINIT_F);
   command = 'uiinit';
   eval(GUILOOP_F);
   set(actiontext, 'String', 'Reset')

elseif strcmp(lower(command),lower('init')) 
   if RunFlag,
      command = 'stop';
      eval(GUILOOP_F);
   end
   set(actiontext, 'String', 'Init')
   gen = 0;
   NIND = NINDNew; SUBPOP = SUBPOPNew;
   CODEREAL = CODEREALNew; OBJ_F = OBJ_FNew;
   dgamesh(OBJ_F);
   command='checkrecombine'; eval(GUILOOP_F);
   command='checkmutate'; eval(GUILOOP_F);
   eval(OPTLOOP_F);
   % command = 'step';
   % eval(GUILOOP_F);
   set(actiontext, 'String', 'Init')

elseif strcmp(lower(command),lower('stop')) 
   MAXGEN = gen;
   % RunFlag = 0;
   set(actiontext, 'String', 'Stop')

elseif strcmp(lower(command),lower('step')) 
   set(actiontext, 'String', 'Step')
   MAXGEN = gen;
   if str2num(get(sl1edit,'String')) < MAXGEN,
      set(sl1,'Value',MAXGEN);
      set(sl1edit,'String',int2str(MAXGEN));
   end
   if ~RunFlag,
      RunFlag = 1;
      eval(OPTLOOP_F);
      RunFlag = 0;
   end 
   set(actiontext, 'String', 'Stop')

elseif strcmp(lower(command),lower('run')) 
   set(actiontext, 'String', 'Run')
   MAXGEN=ceil(str2num(get(sl1edit,'String')));
   if ~RunFlag,
      RunFlag = 1;
      eval(OPTLOOP_F);
      RunFlag = 0;
   end 
   set(actiontext, 'String', 'End')

elseif strcmp(lower(command),lower('save')) 
   if RunFlag,
      command = 'stop';
      eval(GUILOOP_F);
   end
   set(actiontext, 'String', 'Saving')
   eval_str = ['save ', save_str ] ;
   eval( eval_str ) ;
   set(actiontext, 'String', 'Saved')

elseif strcmp(lower(command),lower('load')) 
   if RunFlag,
      command = 'stop';
      eval(GUILOOP_F);
   end
   set(actiontext, 'String', 'Loading')
   eval_str = ['load ', save_str ] ;
   eval( eval_str ) ;
   set(actiontext, 'String', 'Loaded')

elseif strcmp(lower(command),lower('checkrankmax')) 
   if ~RANKMETH, spmax = 2; else spmax = NVAR - 2; end
   SP = min(SP, spmax);
   set(sl9,'Max',spmax);
   set(sl9,'Value',SP);
   set(sl9edit,'String',num2str(SP)); 
   set(sl9text3,'String',int2str(spmax));

elseif strcmp(lower(command),lower('checkrecombine')) 
   valpop2=get(pop2,'Value');
   if valpop2==2,XOV_F='recint';
   elseif valpop2==3,XOV_F='reclin';
   elseif valpop2==4,XOV_F='xovsp';
   elseif valpop2==5,XOV_F='xovdp';
   elseif valpop2==6,XOV_F='xovsh';
   else XOV_F='recdis';end; 
   if CODEREAL,
      if strcmp(lower(XOV_F),'recint'),
         XOV_F='xovsp'; valpop2=4;
      end; 
      if strcmp(lower(XOV_F),'reclin'),
         XOV_F='xovdp'; valpop2=5;
      end;
   end;
   set(pop2,'Value',valpop2);

elseif strcmp(lower(command),lower('checkmutate')) 
   valpop3=get(pop3,'Value');
   if CODEREAL, MUT_F='mutbint'; valpop3=2;
   else MUT_F='mutbga'; valpop3=1;
   end; 
   set(pop3,'Value',valpop3);

elseif strcmp(lower(command),lower('rubbish')) 
   highrun = highrun - high2;
   sl5text1 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left2 highrun 0],... 
      'String','Insertion rate',...
      'VerticalAlignment','bottom') ;
   sl5edit = uicontrol(...
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['INSR=str2num(get(sl5edit,''String''));'...
                  'INSR=min(1,max(0,INSR));'...
                  'set(sl5edit,''String'',num2str(INSR));'... 
                  'set(sl5,''Value'',INSR);'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Position', [left3 highrun wideed high1],...
      'String',num2str(INSR),... 
      'Style','edit',... 
      'Units','normalized',... 
      'Visible','on',... 
      'UserData',['sl5edit']); 
   sl5text2 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left4 highrun 0],... 
      'String','0',...
      'VerticalAlignment','bottom') ;
   sl5 = uicontrol(... 
      'BackgroundColor',[0.7 0.7 0.7 ],... 
      'CallBack',['INSR=get(sl5,''Value'');'...
                  'set(sl5edit,''String'',num2str(INSR));'],... 
      'ForegroundColor',[0 0 0 ],... 
      'Min', 0, 'Max', 1,...
      'Position', [left5 highrun widesl high1],...
      'String','',... 
      'Style','slider',... 
      'Units','normalized',... 
      'Value', INSR, ...
      'Visible','on',... 
      'UserData',['sl5']);
   sl5text3 = text(...
      'Color',[1 1 1 ],... 
      'Position',[left6 highrun 0],... 
      'String','1',...
      'VerticalAlignment','bottom') ;

else 
   error('Error: called with incorrect command.') 

end 


% End of script
